# Generated by Django 2.2.6 on 2019-10-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.CharField(choices=[('W', 'warning'), ('P', 'primary'), ('SE', 'secondary')], max_length=2),
        ),
    ]
