# Generated by Django 2.2.6 on 2019-10-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20191031_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.CharField(choices=[('WARNING', 'warning'), ('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], max_length=9),
        ),
    ]
